//! proptest scaffolding for `contradiction.review` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

proptest! {
    // id: p_proposal_entry
    // generator: proposer runs over seeded stores with valid pairs, repeated pairs, self-pairs, and hallucinated claim keys
    // predicate: valid pairs stage as open proposals with producer provenance and no `contradicts` edge; duplicates, self-pairs, and hallucinated keys are refused honestly
    #[test]
    fn p_proposal_entry() {
        todo_predicate!("valid pairs stage as open proposals with producer provenance and no `contradicts` edge; duplicates, self-pairs, and hallucinated keys are refused honestly");
    }
}

proptest! {
    // id: p_human_resolution
    // generator: resolution attempts through automated paths and the human command, with and without actor identity, over approved and rejected proposals
    // predicate: only explicit actor-identified commands resolve a proposal; approval writes exactly one provenanced `contradicts` edge, rejection writes none; exactly one audit record per resolution
    #[test]
    fn p_human_resolution() {
        todo_predicate!("only explicit actor-identified commands resolve a proposal; approval writes exactly one provenanced `contradicts` edge, rejection writes none; exactly one audit record per resolution");
    }
}

proptest! {
    // id: p_repropose_guard
    // generator: re-proposals of rejected pairs with unchanged and changed fingerprints
    // predicate: unchanged re-proposals are refused with the prior rejection audit intact; changed fingerprints re-queue the pair once
    #[test]
    fn p_repropose_guard() {
        todo_predicate!("unchanged re-proposals are refused with the prior rejection audit intact; changed fingerprints re-queue the pair once");
    }
}

proptest! {
    // id: p_queue_transparency
    // generator: queues with proposals of varied ages, producers, and rationales
    // predicate: the list command returns every open proposal with producer, rationale, and age, oldest-first; nothing is hidden
    #[test]
    fn p_queue_transparency() {
        todo_predicate!("the list command returns every open proposal with producer, rationale, and age, oldest-first; nothing is hidden");
    }
}

proptest! {
    // id: p_scan_untouched
    // generator: scan passes run before, during, and after proposal-queue activity
    // predicate: scan reports and written edges are identical with an empty queue and with queued/resolved proposals present
    #[test]
    fn p_scan_untouched() {
        todo_predicate!("scan reports and written edges are identical with an empty queue and with queued/resolved proposals present");
    }
}

