---- MODULE entityreview ----
\* Generated by `spk compile` from spec `entity.review` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"proposed", "resolved_approved", "resolved_rejected"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "proposed"

Next ==
  \* approve: proposed -> resolved_approved (guard: [[entity.review.er_human_resolution]])
  \/ vpc = "proposed" /\ vpc' = "resolved_approved"
  \* reject: proposed -> resolved_rejected (guard: [[entity.review.er_human_resolution]])
  \/ vpc = "proposed" /\ vpc' = "resolved_rejected"
  \* repropose: resolved_rejected -> proposed (guard: [[entity.review.er_repropose_guard]])
  \/ vpc = "resolved_rejected" /\ vpc' = "proposed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
