//! proptest scaffolding for `entity.review` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn path() -> impl Strategy<Value = GenVal> {
        Just(GenVal("path".into()))
    }

}

proptest! {
    // id: p_queue_entry
    // generator: ER passes over mention streams producing candidates, plus attempts to inject candidates via review commands and synthetic LLM output
    // predicate: every queue entry traces to a `possible_duplicate_of` edge from the deterministic pass; injected candidates are refused; the queue contents equal the open proposal edges
    #[test]
    fn p_queue_entry() {
        todo_predicate!("every queue entry traces to a `possible_duplicate_of` edge from the deterministic pass; injected candidates are refused; the queue contents equal the open proposal edges");
    }
}

proptest! {
    // id: p_human_resolution
    // generator: resolution attempts through every automated path (pipeline stage, re-ingest, batch job) and through the human command, with and without actor identity
    // predicate: only explicit human commands with actor identity resolve a candidate; automated attempts leave it `proposed`; resolutions without actor identity are refused
    #[test]
    fn p_human_resolution(v0 in spec_gen::path()) {
        todo_predicate!("only explicit human commands with actor identity resolve a candidate; automated attempts leave it `proposed`; resolutions without actor identity are refused");
    }
}

proptest! {
    // id: p_merge_preserves
    // generator: approved merges over entity pairs with disjoint, overlapping, and multi-source lineage sets
    // predicate: the merged entity's lineage equals the union of both sides' pre-merge edges; exactly one audit record per resolution with actor, timestamp, both ids, and decision
    #[test]
    fn p_merge_preserves() {
        todo_predicate!("the merged entity's lineage equals the union of both sides' pre-merge edges; exactly one audit record per resolution with actor, timestamp, both ids, and decision");
    }
}

proptest! {
    // id: p_reject_drops_edge
    // generator: rejections over pairs with claims and lineage on both sides
    // predicate: after rejection the `possible_duplicate_of` edge is gone and everything else — entities, lineage, claims, statuses — is unchanged; the audit trail gains one rejection record
    #[test]
    fn p_reject_drops_edge() {
        todo_predicate!("after rejection the `possible_duplicate_of` edge is gone and everything else — entities, lineage, claims, statuses — is unchanged; the audit trail gains one rejection record");
    }
}

proptest! {
    // id: p_repropose_guard
    // generator: re-runs of the deterministic pass over unchanged inputs and inputs with new mentions or alias entries
    // predicate: unchanged-input re-runs never re-queue a rejected pair; new-evidence re-runs re-queue it once with the prior rejection record intact
    #[test]
    fn p_repropose_guard() {
        todo_predicate!("unchanged-input re-runs never re-queue a rejected pair; new-evidence re-runs re-queue it once with the prior rejection record intact");
    }
}

proptest! {
    // id: p_queue_transparency
    // generator: queues with candidates of varied ages, evidence kinds, and claim counts
    // predicate: the list command returns every open candidate with evidence, claim counts, and age, oldest-first; nothing is hidden from the human reviewing it
    #[test]
    fn p_queue_transparency() {
        todo_predicate!("the list command returns every open candidate with evidence, claim counts, and age, oldest-first; nothing is hidden from the human reviewing it");
    }
}

proptest! {
    // id: p_review-schema
    // generator: review-queue records sampled from the published schema
    // predicate: every queue and audit record validates against the published schema with the closed decision vocabulary
    #[test]
    fn p_review_schema() {
        todo_predicate!("every queue and audit record validates against the published schema with the closed decision vocabulary");
    }
}

