//! proptest scaffolding for `extraction.claims` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn duplicates() -> impl Strategy<Value = GenVal> {
        Just(GenVal("duplicates".into()))
    }

}

proptest! {
    // id: p_single_call
    // generator: episode corpora ingested, re-ingested unchanged, and re-ingested with a bumped extractor version
    // predicate: exactly one successful call per (episode id, extractor version); re-ingest at the same version produces no new call and reuses cached output; a version bump re-extracts
    #[test]
    fn p_single_call() {
        todo_predicate!("exactly one successful call per (episode id, extractor version); re-ingest at the same version produces no new call and reuses cached output; a version bump re-extracts");
    }
}

proptest! {
    // id: p_typed_gate
    // generator: candidate records mixing schema-valid, schema-violating, lineage-less, evidence-less, and zero-candidate episodes
    // predicate: only schema-valid lineage-bearing candidates with a passing evidence span reach `validated`; every violation lands in `rejected` unmodified; a zero-candidate episode caches as legitimately empty
    #[test]
    fn p_typed_gate() {
        todo_predicate!("only schema-valid lineage-bearing candidates with a passing evidence span reach `validated`; every violation lands in `rejected` unmodified; a zero-candidate episode caches as legitimately empty");
    }
}

proptest! {
    // id: p_supersession
    // generator: episode corpora re-extracted at bumped extractor versions with prior output in `staged`, `active`, and `rejected` states
    // predicate: only prior-version `staged` claims become `rejected` with reason `superseded-by-reextraction`, lineage and evidence remaining queryable; `active` and `rejected` claims from any version never change status; active conflicts stage invalidation proposals; superseded claims re-enter `staged` only via explicit re-stage
    #[test]
    fn p_supersession() {
        todo_predicate!("only prior-version `staged` claims become `rejected` with reason `superseded-by-reextraction`, lineage and evidence remaining queryable; `active` and `rejected` claims from any version never change status; active conflicts stage invalidation proposals; superseded claims re-enter `staged` only via explicit re-stage");
    }
}

proptest! {
    // id: p_run_record
    // generator: extraction calls with success, repeated-failure, and gate-rejection outcomes
    // predicate: every call writes exactly one run row with episode id, extractor version, model id when present, timestamps, and finish status; every parked episode and gate rejection carries a machine-readable reason; claim nodes expose no reason field
    #[test]
    fn p_run_record() {
        todo_predicate!("every call writes exactly one run row with episode id, extractor version, model id when present, timestamps, and finish status; every parked episode and gate rejection carries a machine-readable reason; claim nodes expose no reason field");
    }
}

proptest! {
    // id: p_evidence_containment
    // generator: candidate spans that are contained, non-contained after whitespace collapse, and typed-absent
    // predicate: contained spans persist verbatim; non-contained spans reject with reason `evidence-not-contained` and are never repaired; typed-absent spans persist flagged by the reflection pass and are never reported as violations
    #[test]
    fn p_evidence_containment() {
        todo_predicate!("contained spans persist verbatim; non-contained spans reject with reason `evidence-not-contained` and are never repaired; typed-absent spans persist flagged by the reflection pass and are never reported as violations");
    }
}

proptest! {
    // id: p_no_llm_post
    // generator: candidate sets containing near-duplicates (simhash distance) and unnormalized fields
    // predicate: identical post-pass inputs produce identical outputs and no LLM call occurs after the extraction step
    #[test]
    fn p_no_llm_post(v0 in spec_gen::duplicates()) {
        todo_predicate!("identical post-pass inputs produce identical outputs and no LLM call occurs after the extraction step");
    }
}

proptest! {
    // id: p_mutation_proposal
    // generator: candidate claims conflicting with seeded active claims
    // predicate: every conflict stages an invalidation proposal citing its causing episode; seeded claims are unchanged until the proposal is applied
    #[test]
    fn p_mutation_proposal() {
        todo_predicate!("every conflict stages an invalidation proposal citing its causing episode; seeded claims are unchanged until the proposal is applied");
    }
}

proptest! {
    // id: p_reflection
    // generator: extracted candidates containing unsupported statements and dropped hedges
    // predicate: reflection flags each unsupported candidate; the post-reflection candidate set introduces no new claims
    #[test]
    fn p_reflection() {
        todo_predicate!("reflection flags each unsupported candidate; the post-reflection candidate set introduces no new claims");
    }
}

proptest! {
    // id: p_tag_inheritance
    // generator: episodes with varying tag sets, derived claim sets, and multi-source claims
    // predicate: every derived claim resolves to exactly the union of its supporting episodes' tag sets via lineage walk; no tag is stored on the claim node
    #[test]
    fn p_tag_inheritance() {
        todo_predicate!("every derived claim resolves to exactly the union of its supporting episodes' tag sets via lineage walk; no tag is stored on the claim node");
    }
}

proptest! {
    // id: p_deterministic_structure
    // generator: episodes with converter-supplied structure markers
    // predicate: structural relations derive from markers alone, independent of extraction output
    #[test]
    fn p_deterministic_structure() {
        todo_predicate!("structural relations derive from markers alone, independent of extraction output");
    }
}

proptest! {
    // id: p_output_schema
    // generator: candidate-claim records sampled from the published schema
    // predicate: the published schema validates every emitted candidate record
    #[test]
    fn p_output_schema() {
        todo_predicate!("the published schema validates every emitted candidate record");
    }
}

