----------------------------------------------------
MODULE extractionclaims
----------------------------------------------------
\* Generated by `spk compile` from spec `extraction.claims` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"pending", "extracted", "validated", "staged", "rejected"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "pending"

Next ==
  \* run: pending -> extracted (guard: [[extraction.claims.ex_single_call]])
  \/ vpc = "pending" /\ vpc' = "extracted"
  \* gate: extracted -> validated (guard: [[extraction.claims.ex_typed_gate]])
  \/ vpc = "extracted" /\ vpc' = "validated"
  \* refuse: extracted -> rejected (guard: [[extraction.claims.ex_typed_gate]])
  \/ vpc = "extracted" /\ vpc' = "rejected"
  \* stage: validated -> staged (guard: [[extraction.claims.ex_no_llm_post]])
  \/ vpc = "validated" /\ vpc' = "staged"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
