//! proptest scaffolding for `extraction.claims` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn duplicates() -> impl Strategy<Value = GenVal> {
        Just(GenVal("duplicates".into()))
    }

}

proptest! {
    // id: p_single_call
    // generator: episode corpora ingested, then re-ingested unchanged
    // predicate: exactly one extraction call per persisted episode id; re-ingest produces no new call and reuses cached output
    #[test]
    fn p_single_call() {
        todo_predicate!("exactly one extraction call per persisted episode id; re-ingest produces no new call and reuses cached output");
    }
}

proptest! {
    // id: p_typed_gate
    // generator: candidate records mixing schema-valid, schema-violating, and lineage-less claims
    // predicate: only schema-valid lineage-bearing candidates reach `staged`; every violation lands in `rejected` unmodified
    #[test]
    fn p_typed_gate() {
        todo_predicate!("only schema-valid lineage-bearing candidates reach `staged`; every violation lands in `rejected` unmodified");
    }
}

proptest! {
    // id: p_no_llm_post
    // generator: candidate sets containing near-duplicates (simhash distance) and unnormalized fields
    // predicate: identical post-pass inputs produce identical outputs and no LLM call occurs after the extraction step
    #[test]
    fn p_no_llm_post(v0 in spec_gen::duplicates()) {
        todo_predicate!("identical post-pass inputs produce identical outputs and no LLM call occurs after the extraction step");
    }
}

proptest! {
    // id: p_mutation_proposal
    // generator: candidate claims conflicting with seeded active claims
    // predicate: every conflict stages an invalidation proposal citing its causing episode; seeded claims are unchanged until the proposal is applied
    #[test]
    fn p_mutation_proposal() {
        todo_predicate!("every conflict stages an invalidation proposal citing its causing episode; seeded claims are unchanged until the proposal is applied");
    }
}

proptest! {
    // id: p_reflection
    // generator: extracted candidates containing unsupported statements and dropped hedges
    // predicate: reflection flags each unsupported candidate; the post-reflection candidate set introduces no new claims
    #[test]
    fn p_reflection() {
        todo_predicate!("reflection flags each unsupported candidate; the post-reflection candidate set introduces no new claims");
    }
}

proptest! {
    // id: p_tag_inheritance
    // generator: episodes with varying tag sets and derived claim sets
    // predicate: every derived claim carries exactly its source episode's tag set
    #[test]
    fn p_tag_inheritance() {
        todo_predicate!("every derived claim carries exactly its source episode's tag set");
    }
}

proptest! {
    // id: p_deterministic_structure
    // generator: episodes with converter-supplied structure markers
    // predicate: structural relations derive from markers alone, independent of extraction output
    #[test]
    fn p_deterministic_structure() {
        todo_predicate!("structural relations derive from markers alone, independent of extraction output");
    }
}

proptest! {
    // id: p_output_schema
    // generator: candidate-claim records sampled from the published schema
    // predicate: the published schema validates every emitted candidate record
    #[test]
    fn p_output_schema() {
        todo_predicate!("the published schema validates every emitted candidate record");
    }
}

