//! proptest scaffolding for `graph.model` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn statements() -> impl Strategy<Value = GenVal> {
        Just(GenVal("statements".into()))
    }

    pub fn path() -> impl Strategy<Value = GenVal> {
        Just(GenVal("path".into()))
    }

}

proptest! {
    // id: p_reified
    // generator: claims extracted from synthetic corpora with known source counts N in 1..4
    // predicate: every claim node has exactly N lineage edges matching its known source count; a zero-source claim is never persisted
    #[test]
    fn p_reified() {
        todo_predicate!("every claim node has exactly N lineage edges matching its known source count; a zero-source claim is never persisted");
    }
}

proptest! {
    // id: p_lineage_survives
    // generator: random sequences of invalidation and episode-deletion operations over a seeded graph
    // predicate: after every operation: each surviving claim's episode edge count equals its supporting-episode count; a claim disappears only when its last supporting episode is deleted
    #[test]
    fn p_lineage_survives() {
        todo_predicate!("after every operation: each surviving claim's episode edge count equals its supporting-episode count; a claim disappears only when its last supporting episode is deleted");
    }
}

proptest! {
    // id: p_deterministic_er
    // generator: mention streams mixing known aliases, unmatched names, and near-duplicates
    // predicate: entity node count changes only via explicit new-node creation or reviewed merges; queue contents equal candidate pairs
    #[test]
    fn p_deterministic_er() {
        todo_predicate!("entity node count changes only via explicit new-node creation or reviewed merges; queue contents equal candidate pairs");
    }
}

proptest! {
    // id: p_merge_keeps
    // generator: human-reviewed merge and rejection operations over seeded entity pairs
    // predicate: approved merges preserve the union of both sides' lineage edges; rejected candidates lose only their `possible_duplicate_of` edge
    #[test]
    fn p_merge_keeps() {
        todo_predicate!("approved merges preserve the union of both sides' lineage edges; rejected candidates lose only their `possible_duplicate_of` edge");
    }
}

proptest! {
    // id: p_schema_v2
    // generator: claim records with extra, missing, and mistyped fields
    // predicate: stored claim nodes expose exactly the eight schema fields with types preserved; evidence is a verbatim span with locator or the typed absent marker
    #[test]
    fn p_schema_v2() {
        todo_predicate!("stored claim nodes expose exactly the eight schema fields with types preserved; evidence is a verbatim span with locator or the typed absent marker");
    }
}

proptest! {
    // id: p_embedded_store
    // generator: seeded graphs of arbitrary size, with and without deletion tombstones
    // predicate: dump-then-recreate from episode stream plus extraction output plus tombstones reproduces the graph exactly, deletions included
    #[test]
    fn p_embedded_store() {
        todo_predicate!("dump-then-recreate from episode stream plus extraction output plus tombstones reproduces the graph exactly, deletions included");
    }
}

proptest! {
    // id: p_hedge_anchor
    // generator: episode texts containing hedged statements (may, signals, estimates)
    // predicate: no derived claim text drops a hedge marker present in its supporting episode; evidence spans preserve hedge markers within their coverage
    #[test]
    fn p_hedge_anchor(v0 in spec_gen::statements()) {
        todo_predicate!("no derived claim text drops a hedge marker present in its supporting episode; evidence spans preserve hedge markers within their coverage");
    }
}

proptest! {
    // id: p_human_adopt
    // generator: adopt attempts driven through every automated path (pipeline stage, re-ingest, merge) and through the human CLI, single and batch
    // predicate: only explicit human accept actions move a claim to `active`; every transition record carries actor and timestamp, one per claim; automated attempts leave the claim `proposed`
    #[test]
    fn p_human_adopt(v0 in spec_gen::path()) {
        todo_predicate!("only explicit human accept actions move a claim to `active`; every transition record carries actor and timestamp, one per claim; automated attempts leave the claim `proposed`");
    }
}

proptest! {
    // id: p_relation_typing
    // generator: edge records sampled from the published vocabulary
    // predicate: every edge label is a member of the published relation set
    #[test]
    fn p_relation_typing() {
        todo_predicate!("every edge label is a member of the published relation set");
    }
}

proptest! {
    // id: p_contradicts_provenance
    // generator: contradiction-scan passes over seeded claim pairs with negation-marker and numeral edit classes, plus pass re-runs and pairs outside the closed classes
    // predicate: every `contradicts` edge the pass writes carries pass identity and detection-rule provenance; a re-run over an already-scanned graph refuses the identical edge rather than doubling it; pairs outside the closed edit classes never propose
    #[test]
    fn p_contradicts_provenance() {
        todo_predicate!("every `contradicts` edge the pass writes carries pass identity and detection-rule provenance; a re-run over an already-scanned graph refuses the identical edge rather than doubling it; pairs outside the closed edit classes never propose");
    }
}

