----------------------------------------------
MODULE graphmodel
----------------------------------------------
\* Generated by `spk compile` from spec `graph.model` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"proposed", "active", "invalid", "merged"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "proposed"

Next ==
  \* adopt: proposed -> active (guard: [[graph.model.gm_reified]])
  \/ vpc = "proposed" /\ vpc' = "active"
  \* invalidate: active -> invalid (guard: [[graph.model.gm_lineage-survives]])
  \/ vpc = "active" /\ vpc' = "invalid"
  \* merge: active -> merged (guard: [[graph.model.gm_deterministic-er]])
  \/ vpc = "active" /\ vpc' = "merged"
  \* repropose: invalid -> proposed (guard: [[graph.model.gm_lineage-survives]])
  \/ vpc = "invalid" /\ vpc' = "proposed"

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
