//! proptest scaffolding for `graph.model` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn statements() -> impl Strategy<Value = GenVal> {
        Just(GenVal("statements".into()))
    }

}

proptest! {
    // id: p.reified
    // generator: arbitrary claim extractions over synthetic episode corpora
    // predicate: every claim node in the resulting graph has at least one episode lineage edge; N-source claims have N edges
    #[test]
    fn p_reified() {
        todo_predicate!("every claim node in the resulting graph has at least one episode lineage edge; N-source claims have N edges");
    }
}

proptest! {
    // id: p.lineage-survives
    // generator: random sequences of invalidation and merge operations over a seeded graph
    // predicate: after every operation: each surviving claim's episode edge count is greater than or equal to its pre-operation count minus deleted episodes
    #[test]
    fn p_lineage_survives() {
        todo_predicate!("after every operation: each surviving claim's episode edge count is greater than or equal to its pre-operation count minus deleted episodes");
    }
}

proptest! {
    // id: p.deterministic-er
    // generator: mention streams mixing known aliases, unmatched names, and near-duplicates
    // predicate: entity node count changes only via explicit new-node creation or reviewed merges; queue contents equal candidate pairs
    #[test]
    fn p_deterministic_er() {
        todo_predicate!("entity node count changes only via explicit new-node creation or reviewed merges; queue contents equal candidate pairs");
    }
}

proptest! {
    // id: p.schema-v1
    // generator: claim records with extra, missing, and mistyped fields
    // predicate: stored claim nodes expose exactly the seven schema fields with types preserved
    #[test]
    fn p_schema_v1() {
        todo_predicate!("stored claim nodes expose exactly the seven schema fields with types preserved");
    }
}

proptest! {
    // id: p.embedded-store
    // generator: seeded graphs of arbitrary size
    // predicate: dump-then-recreate from episode stream plus extraction output reproduces the graph exactly
    #[test]
    fn p_embedded_store() {
        todo_predicate!("dump-then-recreate from episode stream plus extraction output reproduces the graph exactly");
    }
}

proptest! {
    // id: p.hedge-anchor
    // generator: episode texts containing hedged statements (may, signals, estimates)
    // predicate: no derived claim text drops a hedge marker present in its supporting episode
    #[test]
    fn p_hedge_anchor(v0 in spec_gen::statements()) {
        todo_predicate!("no derived claim text drops a hedge marker present in its supporting episode");
    }
}

proptest! {
    // id: p.relation-typing
    // generator: edge records sampled from the published vocabulary
    // predicate: every edge label is a member of the published relation set
    #[test]
    fn p_relation_typing() {
        todo_predicate!("every edge label is a member of the published relation set");
    }
}

