---- MODULE graphmodel ----
\* Generated by `spk compile` from spec `graph.model` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"proposed", "active", "invalid", "rejected"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "proposed"

Next ==
  \* adopt: proposed -> active (guard: [[graph.model.gm_human_adopt]] [[graph.model.gm_reified]])
  \/ vpc = "proposed" /\ vpc' = "active"
  \* discard: proposed -> rejected (guard: [[graph.model.gm_reified]])
  \/ vpc = "proposed" /\ vpc' = "rejected"
  \* invalidate: active -> invalid (guard: [[graph.model.gm_lineage_survives]])
  \/ vpc = "active" /\ vpc' = "invalid"
  \* repropose: invalid -> proposed (guard: [[graph.model.gm_lineage_survives]])
  \/ vpc = "invalid" /\ vpc' = "proposed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
