//! proptest scaffolding for `ingestion.contract` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn artifacts() -> impl Strategy<Value = GenVal> {
        Just(GenVal("artifacts".into()))
    }

}

proptest! {
    // id: p.verbatim
    // generator: arbitrary episode records with random locator forms
    // predicate: persisted episode round-trips: stored text, locator, and metadata equal the submitted record
    #[test]
    fn p_verbatim() {
        todo_predicate!("persisted episode round-trips: stored text, locator, and metadata equal the submitted record");
    }
}

proptest! {
    // id: p.idempotent
    // generator: the same episode stream submitted twice in sequence
    // predicate: graph hash after second ingest equals graph hash after first ingest
    #[test]
    fn p_idempotent() {
        todo_predicate!("graph hash after second ingest equals graph hash after first ingest");
    }
}

proptest! {
    // id: p.no-format-parsing
    // generator: episode streams with arbitrary trailing format artifacts (frontmatter, page markers)
    // predicate: ingest output depends only on stream fields, never on unparsed bytes
    #[test]
    fn p_no_format_parsing(v0 in spec_gen::artifacts()) {
        todo_predicate!("ingest output depends only on stream fields, never on unparsed bytes");
    }
}

proptest! {
    // id: p.date-fidelity
    // generator: episodes with missing, malformed, and valid cutoff dates
    // predicate: stored cutoff equals source cutoff when present, `unknown` otherwise; never ingest time
    #[test]
    fn p_date_fidelity() {
        todo_predicate!("stored cutoff equals source cutoff when present, `unknown` otherwise; never ingest time");
    }
}

proptest! {
    // id: p.stream-schema
    // generator: record instances sampled from the published schema
    // predicate: schema document validates every emitted record
    #[test]
    fn p_stream_schema() {
        todo_predicate!("schema document validates every emitted record");
    }
}

