//! proptest scaffolding for `ingestion.contract` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! predicates not yet translated to Rust fail in `verify` via
//! `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Placeholder element type for generated values; `verify` replaces
/// this scaffolding with real strategies and assertion bodies.
#[derive(Debug, Clone)]
pub struct GenVal(pub String);

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job.
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// The real element types and strategies are `verify`'s domain.
pub mod spec_gen {
    use super::*;

    pub fn artifacts() -> impl Strategy<Value = GenVal> {
        Just(GenVal("artifacts".into()))
    }

    pub fn text() -> impl Strategy<Value = GenVal> {
        Just(GenVal("text".into()))
    }

    pub fn interleaved() -> impl Strategy<Value = GenVal> {
        Just(GenVal("interleaved".into()))
    }

    pub fn class() -> impl Strategy<Value = GenVal> {
        Just(GenVal("class".into()))
    }

}

proptest! {
    // id: p_verbatim
    // generator: arbitrary episode records with random locator forms
    // predicate: persisted episode round-trips: stored text, locator, and metadata equal the submitted record
    #[test]
    fn p_verbatim() {
        todo_predicate!("persisted episode round-trips: stored text, locator, and metadata equal the submitted record");
    }
}

proptest! {
    // id: p_idempotent
    // generator: the same episode stream submitted twice in sequence, plus a mutated variant reusing an existing id with altered text
    // predicate: re-ingest yields a graph identical to the one before it; a mutated re-submission either deterministically updates or is rejected — it never duplicates an episode
    #[test]
    fn p_idempotent() {
        todo_predicate!("re-ingest yields a graph identical to the one before it; a mutated re-submission either deterministically updates or is rejected — it never duplicates an episode");
    }
}

proptest! {
    // id: p_no_format_parsing
    // generator: episode streams with arbitrary trailing format artifacts (frontmatter, page markers)
    // predicate: ingest output depends only on stream fields, never on unparsed bytes
    #[test]
    fn p_no_format_parsing(v0 in spec_gen::artifacts()) {
        todo_predicate!("ingest output depends only on stream fields, never on unparsed bytes");
    }
}

proptest! {
    // id: p_date_fidelity
    // generator: episodes with missing, malformed, and valid cutoff dates
    // predicate: stored cutoff equals source cutoff when present, explicit absent marker otherwise; never ingest time
    #[test]
    fn p_date_fidelity() {
        todo_predicate!("stored cutoff equals source cutoff when present, explicit absent marker otherwise; never ingest time");
    }
}

proptest! {
    // id: p_malformed
    // generator: episode records missing verbatim text (including empty and whitespace-only text), a stable id, or required metadata
    // predicate: no malformed record reaches `persisted`; every malformed record is `rejected`
    #[test]
    fn p_malformed(v0 in spec_gen::text()) {
        todo_predicate!("no malformed record reaches `persisted`; every malformed record is `rejected`");
    }
}

proptest! {
    // id: p_id_canon
    // generator: id pairs differing only by NFC vs NFD form, plus empty and whitespace-only ids
    // predicate: normalization-variant ids resolve to one episode idempotently; empty or whitespace-only ids are rejected
    #[test]
    fn p_id_canon() {
        todo_predicate!("normalization-variant ids resolve to one episode idempotently; empty or whitespace-only ids are rejected");
    }
}

proptest! {
    // id: p_unique_id
    // generator: overlapping streams submitted sequentially and interleaved (concurrently)
    // predicate: exactly one persisted episode per stable id; the interleaved final graph equals the sequential one
    #[test]
    fn p_unique_id(v0 in spec_gen::interleaved()) {
        todo_predicate!("exactly one persisted episode per stable id; the interleaved final graph equals the sequential one");
    }
}

proptest! {
    // id: p_batch_resume
    // generator: streams interrupted after each k of N episodes, then fully re-submitted
    // predicate: the final graph equals the graph of a single uninterrupted submission; no episode is half-persisted
    #[test]
    fn p_batch_resume() {
        todo_predicate!("the final graph equals the graph of a single uninterrupted submission; no episode is half-persisted");
    }
}

proptest! {
    // id: p_outcome_schema
    // generator: streams producing every outcome class (new, duplicate, malformed)
    // predicate: every ingest run emits exactly one outcome record per submitted episode and the published outcome schema validates each record
    #[test]
    fn p_outcome_schema(v0 in spec_gen::class()) {
        todo_predicate!("every ingest run emits exactly one outcome record per submitted episode and the published outcome schema validates each record");
    }
}

proptest! {
    // id: p_stream_schema
    // generator: record instances sampled from the published schema
    // predicate: schema document validates every emitted record
    #[test]
    fn p_stream_schema() {
        todo_predicate!("schema document validates every emitted record");
    }
}

