---- MODULE ingestioncontract ----
\* Generated by `spk compile` from spec `ingestion.contract` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"received", "persisted", "rejected"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "received"

Next ==
  \* accept: received -> persisted (guard: [[ingestion.contract.ic_verbatim]])
  \/ vpc = "received" /\ vpc' = "persisted"
  \* reject: received -> rejected (guard: [[ingestion.contract.ic_malformed]])
  \/ vpc = "received" /\ vpc' = "rejected"
  \* reingest: persisted -> persisted (guard: [[ingestion.contract.ic_idempotent]])
  \/ vpc = "persisted" /\ vpc' = "persisted"
  \* reject_conflict: received -> rejected (guard: [[ingestion.contract.ic_mutated_resubmit]])
  \/ vpc = "received" /\ vpc' = "rejected"
  \* reject_duplicate: received -> rejected (guard: [[ingestion.contract.ic_batch_duplicate]])
  \/ vpc = "received" /\ vpc' = "rejected"
  \* resubmit_corrected: rejected -> persisted (guard: [[ingestion.contract.ic_verbatim]])
  \/ vpc = "rejected" /\ vpc' = "persisted"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
