---- MODULE querytools ----
\* Generated by `spk compile` from spec `query.tools` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* Each State becomes a value in the state variable's range.
StateValues == {"queried", "traversed", "budget_exhausted", "answered"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "queried"

Next ==
  \* walk: queried -> traversed (guard: [[query.tools.qt_lineage_traceable]])
  \/ vpc = "queried" /\ vpc' = "traversed"
  \* stop: traversed -> budget_exhausted (guard: [[query.tools.qt_bounded_traversal]])
  \/ vpc = "traversed" /\ vpc' = "budget_exhausted"
  \* answer: traversed -> answered (guard: [[query.tools.qt_ranking]])
  \/ vpc = "traversed" /\ vpc' = "answered"
  \* answer_truncated: budget_exhausted -> answered (guard: [[query.tools.qt_bounded_traversal]])
  \/ vpc = "budget_exhausted" /\ vpc' = "answered"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
